server:
  port: 8080
  mode: debug  # debug or release

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: your_password
  dbname: ping_pong
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

jwt:
  secret: "your-secret-key-here"
  expire_time: 168  # hours

logger:
  level: "debug"
  filename: "logs/app.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true

redis:
  addr: "localhost:6379"
  password: ""
  db: 0